# Generated by Django 3.1.13 on 2021-11-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('pattern', models.TextField()),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(max_length=15)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpl.pattern')),
            ],
            options={
                'verbose_name': 'Leak',
                'verbose_name_plural': 'Leaks',
            },
        ),
    ]
