version: '3'

volumes:
  production_mysql_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: avanan_production_django
    depends_on:
      - mysql
    env_file:
      - ./.envs/.django
      - ./.envs/.mysql
    ports:
      - "8000:8000"
    command: /start

  dpl:
    build:
      context: .
      dockerfile: ./compose/production/dpl/Dockerfile
    image: avanan_production_dpl
    container_name: dpl
    depends_on:
      - django
    env_file:
      - ./.envs/.django
      - ./.envs/.mysql
    command: /start

  mysql:
    image: mysql:5.7.36
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - production_mysql_data:/var/lib/mysql:Z
    env_file:
      - ./.envs/.mysql
