# Generated by Django 3.1.13 on 2021-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQSQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(default='us-west-2', max_length=20)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('visibility_timeout', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'SQSQueue',
                'verbose_name_plural': 'SQSQueues',
            },
        ),
    ]
